export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';
export const GET_DATA_START = 'GET_DATA_START';

export const SHOW_FILTERS = 'SHOW_FILTERS';
export const FILTER = 'FILTER';
export const CLEAR_FILTER_PARAMS = 'CLEAR_FILTER_PARAMS';



export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_FAIL = 'GET_COMPANIES_FAIL';
export const GET_COMPANIES_START = 'GET_COMPANIES_START';